// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJlq74SzI7AtiLNI6nEELPbRgQillXv-s',
    appId: '1:21631511541:web:7e07ccff517e36af004ebc',
    messagingSenderId: '21631511541',
    projectId: 'lolobybarkati-5f1a6',
    authDomain: 'lolobybarkati-5f1a6.firebaseapp.com',
    storageBucket: 'lolobybarkati-5f1a6.firebasestorage.app',
    measurementId: 'G-GK5TH2YPQR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiPxQX51knc3O0mjYVyhMcbMpXIuDvc8U',
    appId: '1:21631511541:android:33df2c9b363d4d45004ebc',
    messagingSenderId: '21631511541',
    projectId: 'lolobybarkati-5f1a6',
    storageBucket: 'lolobybarkati-5f1a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBEQQ8rTULlScj5FxoSqhRC_GEzHCdb2c',
    appId: '1:21631511541:ios:12f6a75b807cd2dc004ebc',
    messagingSenderId: '21631511541',
    projectId: 'lolobybarkati-5f1a6',
    storageBucket: 'lolobybarkati-5f1a6.firebasestorage.app',
    iosBundleId: 'com.lolo.barkati',
  );
}
